title: Linh Anh Le
logo: "https://github.com/linhanhle/linhanhle.github.io/blob/master/Github%20profile.jpg"
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
